# Generated by Django 5.0.6 on 2024-06-20 01:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_remove_clase_check_clase_clase_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='nombre_apellido',
            new_name='apellidos',
        ),
        migrations.RemoveField(
            model_name='planificacion',
            name='tipo_semana',
        ),
        migrations.AddField(
            model_name='persona',
            name='nombres',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planificacion',
            name='tipo_semana_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asistencia.tiposemana'),
            preserve_default=False,
        ),
    ]
